# site settings
title: Agenda de Transparencia
email: info@directoriolegislativo.org
email_subject: Agenda de Transparencia
baseurl: 'https://agendatransparencia.org' #example: '/agendatransparencia'
basedomain: agendatransparencia.org #ciudadanointeligente.github.io
analytics: 'UA-41822715-10'
texto_introductorio: Estas son las 12 propuestas para una
texto_que_remata:  Agenda de Transparencia para Argentina
texto_bajada: 'Enterate por qué estas políticas son indispensables para avanzar hacia un sistema político más democrático.'

# social
hashtags: "AgendaDeTransparencia"
twitter_username:
twitter_txt: '👦👧👨👩👴👵 %23LxsCiudadanxsQueremos'

#support
support_enabled: false

#partners
partners: true

# build settings
markdown: kramdown

#herokuapp
herokuapp: ''

collections:
  cards:
    output: true
  partners:
    output: true
