# site settings
title: Agenda transparencia
email: prensa@agendatransparencia.org
email_subject: Prensa de agendatransparencia.org
baseurl: 'http://agendatransparencia.org' #example: '/agendatransparencia'
basedomain: agendatransparencia.org #ciudadanointeligente.github.io
analytics: 'UA-41822715-10'
texto_introductorio: Estas son las 12 propuestas para una
texto_que_remata:  Agenda de Transparencia para Argentina
texto_bajada: 'Enterate por qué estas 12 políticas de reforma son indispensables para avanzar hacia un sistema político más democrático.'

# social
hashtags: "AgendaTransparencia,transparencia"
twitter_username:
twitter_txt: '👦👧👨👩👴👵 %23LxsCiudadanxsQueremos'

#support
support_enabled: false

#partners
partners: true

# build settings
markdown: kramdown

#herokuapp
herokuapp: ''

collections:
  cards:
    output: true
  partners:
    output: true
